version: '3'
services:
  ros:
    hostname: bridge
    build: ./ros-bridge
    networks:
      - ros
    command: sleep 1

  drone-connector:
    hostname: drone-connector
    build: ./ros-drone
    environment:
      - ROS_HOSTNAME=drone-connector
    depends_on:
      - ros
    command: /bin/bash -c "export CATKIN_WS=\"~/catkin_ws\" && source /root/bebop_ws/devel/setup.bash && LD_LIBRARY_PATH=/opt/ros/melodic/lib/parrot_arsdk:/opt/ros/melodic/lib/:$LD_LIBRARY_PATH roslaunch bebop_driver bebop_node.launch"
    networks:
        - ros

networks:
  ros:
    driver: bridge