version: "3"

services:
  drone-connector:
    container_name: connector
    hostname: drone-connector
    build: ./ros-drone
    environment:
      - ROS_HOSTNAME=drone-connector
      - ROS_MASTER_URI=http://rosmaster:11311
    command: /bin/bash -c "source /entrypoint.sh; sleep 3; roslaunch bebop_driver bebop_node.launch"
    ports:
      - 43210:43210/udp
    networks:
      - ros

  rosmaster:
    container_name: master
    hostname: rosmaster
    image: ros:melodic
    command: roscore
    networks:
      - ros

  controller:
    container_name: controller
    hostname: controller
    build: ./ros-commander
    environment:
      - ROS_HOSTNAME=controller
      - ROS_MASTER_URI=http://rosmaster:11311
    command: sleep infinity
    volumes:
      - ./code:/root/code
    networks:
      - ros

networks:
  ros:
    driver: bridge