version: "3"

services:
  drone-connector:
    hostname: drone-connector
    build: ./ros-drone
    environment:
      - ROS_HOSTNAME=drone-connector
      - ROS_MASTER_URI=http://rosmaster:11311
    command: /bin/bash -c "source /entrypoint.sh; sleep 3; roslaunch bebop_driver bebop_node.launch"
    ports:
      - 43210:43210/udp
    networks:
      - ros

  rosmaster:
    hostname: rosmaster
    build: ./ros-drone
    command: roscore
    networks:
      - ros

networks:
  ros:
    driver: bridge