version: '3'
services:
  #ros:
  #  hostname: bridge
  #  build: ./ros-bridge
  #  networks:
  #    - ros
  #  command: supervisord -c /etc/supervisor/supervisord.conf
  rosmaster:
    hostname: rosmaster
    build: ./ros-drone
    command: roscore
    #environment:
    #  ROS_MASTER_URI: http://192.168.42.43:11311
    networks:
      - ros
    ports:
      - "11311:11311"
    #command: sleep infinity
  #roscommander:
  #  hostname: roscommander
  #  build: ./ros-commander

networks:
  ros:
    driver: bridge