version: '3'
services:
  ros:
    hostname: bridge
    build: ./ros-bridge
    networks:
      - ros
    command: supervisord -c /etc/supervisor/supervisord.conf

  drone-connector:
    hostname: drone-connector
    build: ./ros-drone
    environment:
      - ROS_HOSTNAME=localhost
      - ROS_MASTER_URI=http://localhost:11311
    depends_on:
      - ros
    #command: roslaunch bebop_driver bebop_node.launch
    command: sleep infinity
    #networks:
    #    - ros
    network_mode: "host"

networks:
  ros:
    driver: bridge
